// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categorias.sql

package db

import (
	"context"
)

const createCategoria = `-- name: CreateCategoria :one
INSERT INTO categorias (nombre, id_Deporte)   
    VALUES ($1, $2) RETURNING id_categoria, nombre, id_deporte
`

type CreateCategoriaParams struct {
	Nombre    string `json:"nombre"`
	IDDeporte int32  `json:"id_deporte"`
}

func (q *Queries) CreateCategoria(ctx context.Context, arg CreateCategoriaParams) (Categoria, error) {
	row := q.db.QueryRowContext(ctx, createCategoria, arg.Nombre, arg.IDDeporte)
	var i Categoria
	err := row.Scan(&i.IDCategoria, &i.Nombre, &i.IDDeporte)
	return i, err
}

const deleteCategoria = `-- name: DeleteCategoria :exec
DELETE FROM categorias WHERE id_Categoria = $1
`

func (q *Queries) DeleteCategoria(ctx context.Context, idCategoria int32) error {
	_, err := q.db.ExecContext(ctx, deleteCategoria, idCategoria)
	return err
}

const getCategoria = `-- name: GetCategoria :one
SELECT id_categoria, nombre, id_deporte FROM categorias WHERE id_Categoria = $1
`

func (q *Queries) GetCategoria(ctx context.Context, idCategoria int32) (Categoria, error) {
	row := q.db.QueryRowContext(ctx, getCategoria, idCategoria)
	var i Categoria
	err := row.Scan(&i.IDCategoria, &i.Nombre, &i.IDDeporte)
	return i, err
}

const listCategorias = `-- name: ListCategorias :many
SELECT id_categoria, nombre, id_deporte FROM categorias
`

func (q *Queries) ListCategorias(ctx context.Context) ([]Categoria, error) {
	rows, err := q.db.QueryContext(ctx, listCategorias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Categoria
	for rows.Next() {
		var i Categoria
		if err := rows.Scan(&i.IDCategoria, &i.Nombre, &i.IDDeporte); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategoria = `-- name: UpdateCategoria :exec
UPDATE categorias SET 
        nombre = $2,
        id_Deporte = $3
    WHERE id_Categoria = $1
`

type UpdateCategoriaParams struct {
	IDCategoria int32  `json:"id_categoria"`
	Nombre      string `json:"nombre"`
	IDDeporte   int32  `json:"id_deporte"`
}

func (q *Queries) UpdateCategoria(ctx context.Context, arg UpdateCategoriaParams) error {
	_, err := q.db.ExecContext(ctx, updateCategoria, arg.IDCategoria, arg.Nombre, arg.IDDeporte)
	return err
}
