// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deportes.sql

package db

import (
	"context"
)

const createDeporte = `-- name: CreateDeporte :one
INSERT INTO deportes (nombre)   
    VALUES ($1) RETURNING id_deporte, nombre
`

func (q *Queries) CreateDeporte(ctx context.Context, nombre string) (Deporte, error) {
	row := q.db.QueryRowContext(ctx, createDeporte, nombre)
	var i Deporte
	err := row.Scan(&i.IDDeporte, &i.Nombre)
	return i, err
}

const deleteDeporte = `-- name: DeleteDeporte :exec
DELETE FROM deportes WHERE id_Deporte = $1
`

func (q *Queries) DeleteDeporte(ctx context.Context, idDeporte int32) error {
	_, err := q.db.ExecContext(ctx, deleteDeporte, idDeporte)
	return err
}

const getDeporte = `-- name: GetDeporte :one
SELECT id_deporte, nombre FROM deportes WHERE id_Deporte = $1
`

func (q *Queries) GetDeporte(ctx context.Context, idDeporte int32) (Deporte, error) {
	row := q.db.QueryRowContext(ctx, getDeporte, idDeporte)
	var i Deporte
	err := row.Scan(&i.IDDeporte, &i.Nombre)
	return i, err
}

const listDeportes = `-- name: ListDeportes :many
SELECT id_deporte, nombre FROM deportes
`

func (q *Queries) ListDeportes(ctx context.Context) ([]Deporte, error) {
	rows, err := q.db.QueryContext(ctx, listDeportes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deporte
	for rows.Next() {
		var i Deporte
		if err := rows.Scan(&i.IDDeporte, &i.Nombre); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeporte = `-- name: UpdateDeporte :exec
UPDATE deportes SET 
        nombre = $2 
    WHERE id_Deporte = $1
`

type UpdateDeporteParams struct {
	IDDeporte int32  `json:"id_deporte"`
	Nombre    string `json:"nombre"`
}

func (q *Queries) UpdateDeporte(ctx context.Context, arg UpdateDeporteParams) error {
	_, err := q.db.ExecContext(ctx, updateDeporte, arg.IDDeporte, arg.Nombre)
	return err
}
