// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inscripciones.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createInscripcion = `-- name: CreateInscripcion :one
INSERT INTO inscripciones (id_Socio, id_Categoria, fechaInscripcion, estado, fechaBaja)
    VALUES ($1, $2, $3, $4, $5) RETURNING id_inscripcion, id_socio, id_categoria, fechainscripcion, estado, fechabaja
`

type CreateInscripcionParams struct {
	IDSocio          int32        `json:"id_socio"`
	IDCategoria      int32        `json:"id_categoria"`
	Fechainscripcion time.Time    `json:"fechainscripcion"`
	Estado           string       `json:"estado"`
	Fechabaja        sql.NullTime `json:"fechabaja"`
}

func (q *Queries) CreateInscripcion(ctx context.Context, arg CreateInscripcionParams) (Inscripcione, error) {
	row := q.db.QueryRowContext(ctx, createInscripcion,
		arg.IDSocio,
		arg.IDCategoria,
		arg.Fechainscripcion,
		arg.Estado,
		arg.Fechabaja,
	)
	var i Inscripcione
	err := row.Scan(
		&i.IDInscripcion,
		&i.IDSocio,
		&i.IDCategoria,
		&i.Fechainscripcion,
		&i.Estado,
		&i.Fechabaja,
	)
	return i, err
}

const deleteInscripcion = `-- name: DeleteInscripcion :exec
DELETE FROM inscripciones WHERE id_Inscripcion = $1
`

func (q *Queries) DeleteInscripcion(ctx context.Context, idInscripcion int32) error {
	_, err := q.db.ExecContext(ctx, deleteInscripcion, idInscripcion)
	return err
}

const getInscripcion = `-- name: GetInscripcion :one
SELECT id_inscripcion, id_socio, id_categoria, fechainscripcion, estado, fechabaja FROM inscripciones WHERE id_Inscripcion = $1
`

func (q *Queries) GetInscripcion(ctx context.Context, idInscripcion int32) (Inscripcione, error) {
	row := q.db.QueryRowContext(ctx, getInscripcion, idInscripcion)
	var i Inscripcione
	err := row.Scan(
		&i.IDInscripcion,
		&i.IDSocio,
		&i.IDCategoria,
		&i.Fechainscripcion,
		&i.Estado,
		&i.Fechabaja,
	)
	return i, err
}

const listInscripciones = `-- name: ListInscripciones :many
SELECT id_inscripcion, id_socio, id_categoria, fechainscripcion, estado, fechabaja FROM inscripciones
`

func (q *Queries) ListInscripciones(ctx context.Context) ([]Inscripcione, error) {
	rows, err := q.db.QueryContext(ctx, listInscripciones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inscripcione
	for rows.Next() {
		var i Inscripcione
		if err := rows.Scan(
			&i.IDInscripcion,
			&i.IDSocio,
			&i.IDCategoria,
			&i.Fechainscripcion,
			&i.Estado,
			&i.Fechabaja,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInscripcion = `-- name: UpdateInscripcion :exec
UPDATE inscripciones SET
        id_Socio = $2,
        id_Categoria = $3,
        fechaInscripcion = $4,
        estado = $5,
        fechaBaja = $6
    WHERE id_Inscripcion = $1
`

type UpdateInscripcionParams struct {
	IDInscripcion    int32        `json:"id_inscripcion"`
	IDSocio          int32        `json:"id_socio"`
	IDCategoria      int32        `json:"id_categoria"`
	Fechainscripcion time.Time    `json:"fechainscripcion"`
	Estado           string       `json:"estado"`
	Fechabaja        sql.NullTime `json:"fechabaja"`
}

func (q *Queries) UpdateInscripcion(ctx context.Context, arg UpdateInscripcionParams) error {
	_, err := q.db.ExecContext(ctx, updateInscripcion,
		arg.IDInscripcion,
		arg.IDSocio,
		arg.IDCategoria,
		arg.Fechainscripcion,
		arg.Estado,
		arg.Fechabaja,
	)
	return err
}
