// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Categoria struct {
	IDCategoria int32  `json:"id_categoria"`
	Nombre      string `json:"nombre"`
	IDDeporte   int32  `json:"id_deporte"`
}

type Deporte struct {
	IDDeporte int32  `json:"id_deporte"`
	Nombre    string `json:"nombre"`
}

type Inscripcione struct {
	IDInscripcion    int32        `json:"id_inscripcion"`
	IDSocio          int32        `json:"id_socio"`
	IDCategoria      int32        `json:"id_categoria"`
	Fechainscripcion time.Time    `json:"fechainscripcion"`
	Estado           string       `json:"estado"`
	Fechabaja        sql.NullTime `json:"fechabaja"`
}

type Practica struct {
	IDPractica  int32     `json:"id_practica"`
	IDCategoria int32     `json:"id_categoria"`
	IDPredio    int32     `json:"id_predio"`
	Diasemana   string    `json:"diasemana"`
	Horainicio  time.Time `json:"horainicio"`
	Horafin     time.Time `json:"horafin"`
}

type Predio struct {
	IDPredio  int32  `json:"id_predio"`
	Nombre    string `json:"nombre"`
	Direccion string `json:"direccion"`
}

type Socio struct {
	IDSocio   int32        `json:"id_socio"`
	IDUsuario int32        `json:"id_usuario"`
	Dni       string       `json:"dni"`
	Fechaalta time.Time    `json:"fechaalta"`
	Fechabaja sql.NullTime `json:"fechabaja"`
}

type Usuario struct {
	ID              int32     `json:"id"`
	Nombre          string    `json:"nombre"`
	Email           string    `json:"email"`
	Contrasena      string    `json:"contrasena"`
	Fechanacimiento time.Time `json:"fechanacimiento"`
	Rol             string    `json:"rol"`
}
