// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: practicas.sql

package db

import (
	"context"
	"time"
)

const createPractica = `-- name: CreatePractica :one
INSERT INTO practicas (id_Categoria, id_Predio, diaSemana, horaInicio, horaFin)
VALUES ($1, $2, $3, $4, $5)
RETURNING id_practica, id_categoria, id_predio, diasemana, horainicio, horafin
`

type CreatePracticaParams struct {
	IDCategoria int32     `json:"id_categoria"`
	IDPredio    int32     `json:"id_predio"`
	Diasemana   string    `json:"diasemana"`
	Horainicio  time.Time `json:"horainicio"`
	Horafin     time.Time `json:"horafin"`
}

func (q *Queries) CreatePractica(ctx context.Context, arg CreatePracticaParams) (Practica, error) {
	row := q.db.QueryRowContext(ctx, createPractica,
		arg.IDCategoria,
		arg.IDPredio,
		arg.Diasemana,
		arg.Horainicio,
		arg.Horafin,
	)
	var i Practica
	err := row.Scan(
		&i.IDPractica,
		&i.IDCategoria,
		&i.IDPredio,
		&i.Diasemana,
		&i.Horainicio,
		&i.Horafin,
	)
	return i, err
}

const deletePractica = `-- name: DeletePractica :exec
DELETE FROM practicas WHERE id_Practica = $1
`

func (q *Queries) DeletePractica(ctx context.Context, idPractica int32) error {
	_, err := q.db.ExecContext(ctx, deletePractica, idPractica)
	return err
}

const getPractica = `-- name: GetPractica :one
SELECT id_practica, id_categoria, id_predio, diasemana, horainicio, horafin
FROM practicas WHERE id_Practica = $1
`

func (q *Queries) GetPractica(ctx context.Context, idPractica int32) (Practica, error) {
	row := q.db.QueryRowContext(ctx, getPractica, idPractica)
	var i Practica
	err := row.Scan(
		&i.IDPractica,
		&i.IDCategoria,
		&i.IDPredio,
		&i.Diasemana,
		&i.Horainicio,
		&i.Horafin,
	)
	return i, err
}

const listPracticas = `-- name: ListPracticas :many
SELECT id_practica, id_categoria, id_predio, diasemana, horainicio, horafin
FROM practicas
`

func (q *Queries) ListPracticas(ctx context.Context) ([]Practica, error) {
	rows, err := q.db.QueryContext(ctx, listPracticas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Practica
	for rows.Next() {
		var i Practica
		if err := rows.Scan(
			&i.IDPractica,
			&i.IDCategoria,
			&i.IDPredio,
			&i.Diasemana,
			&i.Horainicio,
			&i.Horafin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePractica = `-- name: UpdatePractica :exec
UPDATE practicas SET 
        id_Categoria = $2, 
        id_Predio = $3, 
        diaSemana = $4, 
        horaInicio = $5, 
        horaFin = $6 
    WHERE id_Practica = $1
`

type UpdatePracticaParams struct {
	IDPractica  int32     `json:"id_practica"`
	IDCategoria int32     `json:"id_categoria"`
	IDPredio    int32     `json:"id_predio"`
	Diasemana   string    `json:"diasemana"`
	Horainicio  time.Time `json:"horainicio"`
	Horafin     time.Time `json:"horafin"`
}

func (q *Queries) UpdatePractica(ctx context.Context, arg UpdatePracticaParams) error {
	_, err := q.db.ExecContext(ctx, updatePractica,
		arg.IDPractica,
		arg.IDCategoria,
		arg.IDPredio,
		arg.Diasemana,
		arg.Horainicio,
		arg.Horafin,
	)
	return err
}
