// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: predios.sql

package db

import (
	"context"
)

const createPredio = `-- name: CreatePredio :one
INSERT INTO predios (nombre, direccion)
    VALUES ($1, $2) RETURNING id_predio, nombre, direccion
`

type CreatePredioParams struct {
	Nombre    string `json:"nombre"`
	Direccion string `json:"direccion"`
}

func (q *Queries) CreatePredio(ctx context.Context, arg CreatePredioParams) (Predio, error) {
	row := q.db.QueryRowContext(ctx, createPredio, arg.Nombre, arg.Direccion)
	var i Predio
	err := row.Scan(&i.IDPredio, &i.Nombre, &i.Direccion)
	return i, err
}

const deletePredio = `-- name: DeletePredio :exec
DELETE FROM predios WHERE id_Predio = $1
`

func (q *Queries) DeletePredio(ctx context.Context, idPredio int32) error {
	_, err := q.db.ExecContext(ctx, deletePredio, idPredio)
	return err
}

const getPredio = `-- name: GetPredio :one
SELECT id_predio, nombre, direccion FROM predios WHERE id_Predio = $1
`

func (q *Queries) GetPredio(ctx context.Context, idPredio int32) (Predio, error) {
	row := q.db.QueryRowContext(ctx, getPredio, idPredio)
	var i Predio
	err := row.Scan(&i.IDPredio, &i.Nombre, &i.Direccion)
	return i, err
}

const listPredios = `-- name: ListPredios :many
SELECT id_predio, nombre, direccion FROM predios
`

func (q *Queries) ListPredios(ctx context.Context) ([]Predio, error) {
	rows, err := q.db.QueryContext(ctx, listPredios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Predio
	for rows.Next() {
		var i Predio
		if err := rows.Scan(&i.IDPredio, &i.Nombre, &i.Direccion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePredio = `-- name: UpdatePredio :exec
UPDATE predios SET
        nombre = $2,
        direccion = $3
    WHERE id_Predio = $1
`

type UpdatePredioParams struct {
	IDPredio  int32  `json:"id_predio"`
	Nombre    string `json:"nombre"`
	Direccion string `json:"direccion"`
}

func (q *Queries) UpdatePredio(ctx context.Context, arg UpdatePredioParams) error {
	_, err := q.db.ExecContext(ctx, updatePredio, arg.IDPredio, arg.Nombre, arg.Direccion)
	return err
}
