// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: socios.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createSocio = `-- name: CreateSocio :one
INSERT INTO socios (id_Usuario, dni, fechaAlta, fechaBaja)
    VALUES ($1, $2, $3, $4) RETURNING id_socio, id_usuario, dni, fechaalta, fechabaja
`

type CreateSocioParams struct {
	IDUsuario int32        `json:"id_usuario"`
	Dni       string       `json:"dni"`
	Fechaalta time.Time    `json:"fechaalta"`
	Fechabaja sql.NullTime `json:"fechabaja"`
}

func (q *Queries) CreateSocio(ctx context.Context, arg CreateSocioParams) (Socio, error) {
	row := q.db.QueryRowContext(ctx, createSocio,
		arg.IDUsuario,
		arg.Dni,
		arg.Fechaalta,
		arg.Fechabaja,
	)
	var i Socio
	err := row.Scan(
		&i.IDSocio,
		&i.IDUsuario,
		&i.Dni,
		&i.Fechaalta,
		&i.Fechabaja,
	)
	return i, err
}

const deleteSocio = `-- name: DeleteSocio :exec
DELETE FROM socios WHERE id_Socio = $1
`

func (q *Queries) DeleteSocio(ctx context.Context, idSocio int32) error {
	_, err := q.db.ExecContext(ctx, deleteSocio, idSocio)
	return err
}

const getSocio = `-- name: GetSocio :one
SELECT id_socio, id_usuario, dni, fechaalta, fechabaja FROM socios WHERE id_Socio = $1
`

func (q *Queries) GetSocio(ctx context.Context, idSocio int32) (Socio, error) {
	row := q.db.QueryRowContext(ctx, getSocio, idSocio)
	var i Socio
	err := row.Scan(
		&i.IDSocio,
		&i.IDUsuario,
		&i.Dni,
		&i.Fechaalta,
		&i.Fechabaja,
	)
	return i, err
}

const listSocios = `-- name: ListSocios :many
SELECT id_socio, id_usuario, dni, fechaalta, fechabaja FROM socios
`

func (q *Queries) ListSocios(ctx context.Context) ([]Socio, error) {
	rows, err := q.db.QueryContext(ctx, listSocios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Socio
	for rows.Next() {
		var i Socio
		if err := rows.Scan(
			&i.IDSocio,
			&i.IDUsuario,
			&i.Dni,
			&i.Fechaalta,
			&i.Fechabaja,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSocio = `-- name: UpdateSocio :exec
UPDATE socios SET 
        id_Usuario = $2, 
        dni = $3, 
        fechaAlta = $4, 
        fechaBaja = $5
    WHERE id_Socio = $1
`

type UpdateSocioParams struct {
	IDSocio   int32        `json:"id_socio"`
	IDUsuario int32        `json:"id_usuario"`
	Dni       string       `json:"dni"`
	Fechaalta time.Time    `json:"fechaalta"`
	Fechabaja sql.NullTime `json:"fechabaja"`
}

func (q *Queries) UpdateSocio(ctx context.Context, arg UpdateSocioParams) error {
	_, err := q.db.ExecContext(ctx, updateSocio,
		arg.IDSocio,
		arg.IDUsuario,
		arg.Dni,
		arg.Fechaalta,
		arg.Fechabaja,
	)
	return err
}
