// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuarios.sql

package db

import (
	"context"
	"time"
)

const createUsuario = `-- name: CreateUsuario :one
INSERT INTO usuarios (nombre, email, contrasena, fechaNacimiento, rol)
    VALUES ($1, $2, $3, $4, $5) RETURNING id, nombre, email, contrasena, fechanacimiento, rol
`

type CreateUsuarioParams struct {
	Nombre          string    `json:"nombre"`
	Email           string    `json:"email"`
	Contrasena      string    `json:"contrasena"`
	Fechanacimiento time.Time `json:"fechanacimiento"`
	Rol             string    `json:"rol"`
}

func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, createUsuario,
		arg.Nombre,
		arg.Email,
		arg.Contrasena,
		arg.Fechanacimiento,
		arg.Rol,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Email,
		&i.Contrasena,
		&i.Fechanacimiento,
		&i.Rol,
	)
	return i, err
}

const deleteUsuario = `-- name: DeleteUsuario :exec
DELETE FROM usuarios WHERE id = $1
`

func (q *Queries) DeleteUsuario(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUsuario, id)
	return err
}

const getUsuario = `-- name: GetUsuario :one
SELECT id, nombre, email, contrasena, fechanacimiento, rol FROM usuarios WHERE id = $1
`

func (q *Queries) GetUsuario(ctx context.Context, id int32) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuario, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Email,
		&i.Contrasena,
		&i.Fechanacimiento,
		&i.Rol,
	)
	return i, err
}

const listUsuarios = `-- name: ListUsuarios :many
SELECT id, nombre, email, contrasena, fechanacimiento, rol FROM usuarios
`

func (q *Queries) ListUsuarios(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, listUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Email,
			&i.Contrasena,
			&i.Fechanacimiento,
			&i.Rol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUsuario = `-- name: UpdateUsuario :exec
UPDATE usuarios SET 
        nombre = $2, 
        email = $3, 
        contrasena = $4, 
        fechaNacimiento = $5, 
        rol = $6 
    WHERE id = $1
`

type UpdateUsuarioParams struct {
	ID              int32     `json:"id"`
	Nombre          string    `json:"nombre"`
	Email           string    `json:"email"`
	Contrasena      string    `json:"contrasena"`
	Fechanacimiento time.Time `json:"fechanacimiento"`
	Rol             string    `json:"rol"`
}

func (q *Queries) UpdateUsuario(ctx context.Context, arg UpdateUsuarioParams) error {
	_, err := q.db.ExecContext(ctx, updateUsuario,
		arg.ID,
		arg.Nombre,
		arg.Email,
		arg.Contrasena,
		arg.Fechanacimiento,
		arg.Rol,
	)
	return err
}
